-- Attachments for Issues, stored via a swappable storage adapter (see
-- frontend/src/services/storage/). `storage_provider` records which adapter uploaded the
-- file so a future switch (e.g. to a self-hosted backend) doesn't break old rows.
-- Run AFTER schema_issue_tracking_v2.sql.

create table if not exists attachments (
  id uuid primary key default gen_random_uuid(),
  issue_id uuid not null references issues(id) on delete cascade,
  storage_provider text not null default 'supabase',
  url text not null,
  file_name text not null,
  file_size integer,
  content_type text,
  created_at timestamptz not null default now()
);

create index if not exists idx_attachments_issue on attachments (issue_id);

alter table attachments enable row level security;

create policy "project access - attachments select" on attachments for select
  using (has_project_access((select project_id from issues where id = issue_id)));
create policy "issue managers - attachments insert" on attachments for insert
  with check (can_manage_issues((select project_id from issues where id = issue_id)));
create policy "issue managers - attachments delete" on attachments for delete
  using (can_manage_issues((select project_id from issues where id = issue_id)));

-- === Supabase Storage bucket + policies ===
-- Bucket is private (not public) — reads go through signed URLs generated by the adapter.

insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do nothing;

create policy "approved users - attachments storage read" on storage.objects for select
  using (bucket_id = 'attachments' and is_approved());
create policy "approved users - attachments storage insert" on storage.objects for insert
  with check (bucket_id = 'attachments' and is_approved());
create policy "approved users - attachments storage delete" on storage.objects for delete
  using (bucket_id = 'attachments' and is_approved());
